wai-extra: require ansi-terminal >= 0.4 and wai >= 3.2.2.1
Otherwise for earlier `ansi-terminal` one gets
```
Network/Wai/Middleware/RequestLogger.hs:347:15: error:
    Not in scope: type constructor or class ‘Color’
    |
347 | ansiColor' :: Color -> BS.ByteString -> [BS.ByteString]
    |               ^^^^^

Network/Wai/Middleware/RequestLogger.hs:408:25: error:
    Not in scope: type constructor or class ‘Color’
    |
408 |                     -> (Color -> BS.ByteString -> [BS.ByteString])
    |
```
and for earlier `wai`:
```
Network/Wai/Middleware/RequestLogger.hs:53:5: error:
    Module ‘Network.Wai’ does not export ‘getRequestBodyChunk’
   |
53 |   , getRequestBodyChunk
   |     ^^^^^
```